/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDetectRouteImport } from './routes/api/detect'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDetectRoute = ApiDetectRouteImport.update({
  id: '/api/detect',
  path: '/api/detect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/upload': typeof UploadRoute
  '/api/detect': typeof ApiDetectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/upload': typeof UploadRoute
  '/api/detect': typeof ApiDetectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulator': typeof SimulatorRoute
  '/upload': typeof UploadRoute
  '/api/detect': typeof ApiDetectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulator' | '/upload' | '/api/detect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulator' | '/upload' | '/api/detect'
  id: '__root__' | '/' | '/simulator' | '/upload' | '/api/detect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimulatorRoute: typeof SimulatorRoute
  UploadRoute: typeof UploadRoute
  ApiDetectRoute: typeof ApiDetectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/detect': {
      id: '/api/detect'
      path: '/api/detect'
      fullPath: '/api/detect'
      preLoaderRoute: typeof ApiDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimulatorRoute: SimulatorRoute,
  UploadRoute: UploadRoute,
  ApiDetectRoute: ApiDetectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
